version: '3.1'
services:
  app:
    container_name: assessment
    build: .
    ports:
      - "8080-8080"
    depends_on:
      - PostgreSQL
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/assessmentdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
  PostgreSQL:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=assessmentdb